### ISSUE TITLE
noise multiplier too low

### ISSUE THREAD

**Issue by moshebeutel** [xiyuanyang45/DP-pFL#4]
Hi
when computing noise multiplier you need to compute the number of times each data sample is exposed. 
The` local_epoch * (client_data_size / batch_size) * global_epoch ` would fit if the local updates were run on `local_epoch ` batches. But this is not the case. The code in local_update runs all client data for local_epoch times so the all data samples are exposed
 `global_epoch` times
Is that correct?

**Comment by xiyuanyang45** [comment]
Yeah that's true, that opacus package used to work, but I believe that function has changed in usage recently
I turned to use the 
`dp_accounting.rdp.RdpAccountant`
pkg in recent dp works.
Some examples in [tf_dp_tutorial](https://tensorflow.google.cn/federated/tutorials/federated_learning_with_differential_privacy)
